server:
  port: 8080

spring:
  application:
    name: inventory-api

  datasource:
    url: jdbc:postgresql://db.dgufnkbmwaxtjtpdvvcn.supabase.co:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 7975433262#santu
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: "super-secret-key-at-least-32-characters-long-for-hs512"
    expiration-ms: 86400000 # 24 hours

logging:
  level:
    org.springframework.security: DEBUG
    com.example.inventory: DEBUG