package com.example.inventory.enums;

public enum AuditAction {
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DEACTIVATED,
    ORDER_CONFIRMED,
    ORDER_CANCELLED,
    ORDER_PROCESSING_STARTED,
    ORDER_COMPLETED,
    INVENTORY_TRANSFER_CREATED,
    MANUAL_INVENTORY_ADJUSTMENT,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGOUT,
    USER_REGISTERED
}
